name: fresh_flutter
description: A fresh flutter app template

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  provider: ^4.0.4
  flutter_fimber: ^0.3.2
  flutter_vector_icons: ^0.2.1
  flutter_svg: ^0.17.1
  padder: ^1.2.0
  shared_preferences: ^0.5.6+1
  streaming_shared_preferences: ^1.0.1
  get_it: ^3.1.0
  rxdart: any
  auto_size_text: ^2.1.0
  after_layout: ^1.0.7+2
  url_launcher: ^5.4.1
  kt_dart: ^0.6.2
  intl: any
  dio: ^3.0.8
  dio_flutter_transformer: ^3.0.2
  tuple: any
  package_info: ^0.4.0+13
  flutter_advanced_networkimage: ^0.7.0
  system_proxy: ^0.0.1
  keel: ^0.0.4
#  firebase_crashlytics: ^0.1.0+3
#  firebase_analytics: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true